CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE place_primary_type AS ENUM (
  'MUSEUM', 'ART_GALLERY', 'ATTRACTION', 'TEMPLE', 
  'MARKET', 'NATURE', 'PERFORMANCE_VENUE', 'HISTORIC_SITE'
);

CREATE TYPE indoor_outdoor AS ENUM ('INDOOR', 'OUTDOOR', 'MIXED');

CREATE TYPE visit_form AS ENUM ('DAY_TRIP', 'STAY_1_3', 'THEME_TOUR');

CREATE TYPE event_type AS ENUM ('PERFORMANCE', 'EXHIBITION', 'FESTIVAL');

CREATE TYPE event_genre AS ENUM (
  'TRADITIONAL_MUSIC', 'DANCE', 'MUSICAL', 'CLASSICAL',
  'NON_VERBAL', 'MODERN_ART', 'ETC'
);

CREATE TYPE event_status AS ENUM ('ACTIVE', 'CANCELED', 'CLOSED');

CREATE TYPE translation_source AS ENUM (
  'OFFICIAL_HUMAN', 'OFFICIAL_SITE_LAYER', 'MT_GLOSSARY',
  'MT_GLOSSARY_AI_POSTEDIT', 'LLM_GENERATED', 
  'LLM_LOCAL_QWEN_GENERATED', 'MANUAL_EDITOR'
);

CREATE TYPE quality_grade AS ENUM ('A', 'B', 'B_MINUS', 'C');

CREATE TYPE theme_code AS ENUM (
  'HISTORY', 'TRADITIONAL_MUSIC', 'MODERN_ART', 'FAMILY',
  'NIGHT', 'WELLNESS', 'FOOD', 'FESTIVAL'
);

CREATE TYPE slot_type AS ENUM ('MORNING', 'LUNCH', 'AFTERNOON', 'EVENING', 'NIGHT');

CREATE TYPE source_name AS ENUM (
  'TOURAPI', 'MUSEUM_STD', 'KOPIS', 'EMUSEUM', 
  'CULTURE_DATA', 'KMA', 'MANUAL'
);
